apiVersion: v1
kind: Service
metadata:
  name: postgres-runner-service
spec:
  selector:
    app: postgres-runner
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
